"""Remove unused columns on repositories

Revision ID: 19ea01e48843
Revises: 7095f5c0ef18
Create Date: 2025-06-06 18:26:56.783552+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19ea01e48843"
down_revision: Union[str, None] = "7095f5c0ef18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "url")
    op.drop_column("repositories", "open_issues")
    op.drop_column("repositories", "updated_at")
    op.drop_column("repositories", "name")
    op.drop_column("repositories", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repositories",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "repositories",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "repositories",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "repositories",
        sa.Column("open_issues", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "repositories",
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
