"""remove dependency version table

Revision ID: 4a4d201d5e00
Revises: 0b1adaba6815
Create Date: 2025-06-10 09:42:29.298906+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4a4d201d5e00'
down_revision: Union[str, None] = '0b1adaba6815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dependency_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_version',
    sa.Column('dependency_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], name=op.f('dependency_version_dependency_id_fkey')),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], name=op.f('dependency_version_version_id_fkey')),
    sa.PrimaryKeyConstraint('dependency_id', 'version_id', name=op.f('dependency_version_pkey'))
    )
    # ### end Alembic commands ###
