"""make version specific to a dependency

Revision ID: 5b4e6d22b0ac
Revises: 80f78b644553
Create Date: 2025-06-10 17:48:47.605522+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b4e6d22b0ac"
down_revision: Union[str, None] = "80f78b644553"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("versions", sa.Column("dependency_id", sa.Integer(), nullable=False))
    op.create_unique_constraint(None, "versions", ["version", "dependency_id"])
    op.create_foreign_key(None, "versions", "dependencies", ["dependency_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "versions", type_="foreignkey")
    op.drop_constraint(None, "versions", type_="unique")
    op.drop_column("versions", "dependency_id")
    # ### end Alembic commands ###
