"""remove repository dependency table

Revision ID: 80f78b644553
Revises: 4a4d201d5e00
Create Date: 2025-06-10 10:27:35.443422+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80f78b644553'
down_revision: Union[str, None] = '4a4d201d5e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_dependency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_dependency',
    sa.Column('repository_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dependency_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], name=op.f('repository_dependency_dependency_id_fkey')),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('repository_dependency_repository_id_fkey')),
    sa.PrimaryKeyConstraint('repository_id', 'dependency_id', name=op.f('repository_dependency_pkey'))
    )
    # ### end Alembic commands ###
