"""move versions to own table

Revision ID: c362a2813ad2
Revises: 6bf0ff096894
Create Date: 2025-06-10 09:07:42.214198+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c362a2813ad2'
down_revision: Union[str, None] = '6bf0ff096894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependency_version',
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('dependency_id', 'version_id')
    )
    op.create_table('version_vulnerability',
    sa.Column('dependency_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['versions.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('dependency_id', 'vulnerability_id')
    )
    op.drop_table('dependency_vulnerability')
    op.drop_column('dependencies', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependencies', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('dependency_vulnerability',
    sa.Column('dependency_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vulnerability_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], name=op.f('dependency_vulnerability_dependency_id_fkey')),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], name=op.f('dependency_vulnerability_vulnerability_id_fkey')),
    sa.PrimaryKeyConstraint('dependency_id', 'vulnerability_id', name=op.f('dependency_vulnerability_pkey'))
    )
    op.drop_table('version_vulnerability')
    op.drop_table('dependency_version')
    op.drop_table('versions')
    # ### end Alembic commands ###
