version: "3.7"
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  api:
    build:
      context: api
      dockerfile: Dockerfile
    command: fastapi run main.py
    tty: true
    volumes:
      - ./api:/api/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_USER: "dev-user"
      DATABASE_PASSWORD: "password"
      DATABASE_URL: "postgres"
      DATABASE_NAME: "dev-db"
    depends_on:
      - "postgres"
    ports:
      - 8000:8000

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  db-data:
  pgadmin-data:
  # test-db-data:
