name: Run Alembic Migrations
description: Sets up Python, installs dependencies via Poetry, and runs Alembic migrations.

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.11"
  app-dir:
    description: Path to the Python app directory
    required: false
    default: "app"
  database-url:
    description: Full DATABASE_URL for Alembic
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Python dependencies
      shell: bash
      run: |
        cd ${{ inputs.app-dir }}
        poetry install

    - name: Run Alembic migrations
      shell: bash
      run: |
        cd ${{ inputs.app-dir }}
        export DATABASE_URL=${{ inputs.database-url }}
        poetry run alembic upgrade head