"""Add url fetch failure and reason

Revision ID: 1f0271d16689
Revises: 77abd35aa613
Create Date: 2025-06-20 07:03:32.016826+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f0271d16689"
down_revision: Union[str, None] = "77abd35aa613"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dependencies",
        sa.Column(
            "github_url_resolve_failed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "dependencies",
        sa.Column("github_url_resolve_failed_reason", sa.String(), nullable=True),
    )
    op.create_index(
        op.f("ix_dependencies_github_url_resolve_failed"),
        "dependencies",
        ["github_url_resolve_failed"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dependencies_github_url_resolve_failed"), table_name="dependencies"
    )
    op.drop_column("dependencies", "github_url_resolve_failed_reason")
    op.drop_column("dependencies", "github_url_resolve_failed")
    # ### end Alembic commands ###
