"""Update repository table columns to more reasonable values

Revision ID: 2a4b2566e2a9
Revises: 1f0271d16689
Create Date: 2025-06-26 16:41:13.849260+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a4b2566e2a9'
down_revision: Union[str, None] = '1f0271d16689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column(
        'scan_day', 
        sa.Integer(), 
        nullable=False,
        server_default=sa.text("0"),
    ))
    op.add_column('repositories', sa.Column(
        'scan_hour', 
        sa.Integer(), 
        nullable=False,
        server_default=sa.text("0"),
    ))
    op.add_column('repositories', sa.Column(
        'scan_status', 
        sa.String(), 
        nullable=False,
        server_default=sa.text("'pending'"),
    ))
    op.add_column('repositories', sa.Column('error_message', sa.String(), nullable=True))

    op.execute("UPDATE repositories SET clone_url = '' where clone_url IS NULL")

    op.alter_column('repositories', 'clone_url', new_column_name='url', nullable=False)
    op.alter_column('repositories', 'scanned_date', new_column_name='last_scanned_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'url', new_column_name='clone_url', nullable=True)
    op.alter_column('repositories', 'last_scanned_at', new_column_name='scanned_date')
    op.drop_column('repositories', 'error_message')
    op.drop_column('repositories', 'scan_status')
    op.drop_column('repositories', 'scan_hour')
    op.drop_column('repositories', 'scan_day')
    # ### end Alembic commands ###
