"""Add status column to dependencies and clean up other column names

Revision ID: 3dc09bffd5da
Revises: 2a4b2566e2a9
Create Date: 2025-07-06 10:20:00.599574+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dc09bffd5da'
down_revision: Union[str, None] = '2a4b2566e2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dependencies", "github_url_checked_at", new_column_name="scanned_at")
    op.alter_column("dependencies", "github_url_resolve_failed_reason", new_column_name="error_message")
    op.alter_column("dependency_repository", "github_url", new_column_name="repository_url")
    op.add_column('dependencies', sa.Column('scan_status', sa.String(), nullable=False, server_default=sa.text("'pending'") ))
    op.drop_index(op.f('ix_dependencies_github_url_resolve_failed'), table_name='dependencies')
    op.drop_column('dependencies', 'github_url_resolved')
    op.drop_column('dependencies', 'github_url_resolve_failed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column("dependencies", "scanned_at", new_column_name="github_url_checked_at")
    op.alter_column("dependencies", "error_message", new_column_name="github_url_resolve_failed_reason")
    op.alter_column("dependency_repository", "repository_url", new_column_name="github_url")
    op.add_column('dependencies', sa.Column('github_url_resolve_failed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('dependencies', sa.Column('github_url_resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_dependencies_github_url_resolve_failed'), 'dependencies', ['github_url_resolve_failed'], unique=False)
    op.drop_column('dependencies', 'scan_status')
    # ### end Alembic commands ###
