"""Add github detail columns to dependency table

Revision ID: 49823a158fb2
Revises: 83d4ffb8473c
Create Date: 2025-06-18 16:31:04.391555+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49823a158fb2'
down_revision: Union[str, None] = '83d4ffb8473c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependencies', sa.Column('github_url', sa.String(), nullable=True))
    op.add_column('dependencies', sa.Column('github_url_resolved', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('dependencies', sa.Column('github_url_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dependencies', 'github_url_checked_at')
    op.drop_column('dependencies', 'github_url_resolved')
    op.drop_column('dependencies', 'github_url')
    # ### end Alembic commands ###
