"""Add access token column to users table

Revision ID: 7095f5c0ef18
Revises: d03f1b6980cd
Create Date: 2025-06-03 16:30:30.198117+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7095f5c0ef18"
down_revision: Union[str, None] = "d03f1b6980cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("access_token", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "access_token")
    # ### end Alembic commands ###
