"""Add dependency repository table

Revision ID: 77abd35aa613
Revises: 49823a158fb2
Create Date: 2025-06-19 18:06:13.986157+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77abd35aa613"
down_revision: Union[str, None] = "49823a158fb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dependency_repository",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("github_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_url"),
    )
    op.create_index(
        op.f("ix_dependency_repository_id"),
        "dependency_repository",
        ["id"],
        unique=False,
    )
    op.add_column(
        "dependencies",
        sa.Column("dependency_repository_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "dependencies",
        "dependency_repository",
        ["dependency_repository_id"],
        ["id"],
    )
    op.drop_column("dependencies", "github_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dependencies",
        sa.Column("github_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "dependencies", type_="foreignkey")
    op.drop_column("dependencies", "dependency_repository_id")
    op.drop_index(
        op.f("ix_dependency_repository_id"), table_name="dependency_repository"
    )
    op.drop_table("dependency_repository")
    # ### end Alembic commands ###
