"""Add scanned_date column to repositories

Revision ID: 83d4ffb8473c
Revises: 142e721d7148
Create Date: 2025-06-17 16:31:36.253600+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83d4ffb8473c"
down_revision: Union[str, None] = "142e721d7148"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repositories",
        sa.Column("scanned_date", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "scanned_date")
    # ### end Alembic commands ###
