"""Add status column to dependencies and clean up other column names

Revision ID: ac9be663ac69
Revises: 2a4b2566e2a9
Create Date: 2025-07-05 05:31:05.953508+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ac9be663ac69'
down_revision: Union[str, None] = '2a4b2566e2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dependencies", "github_url_checked_at", new_column_name="repository_url_checked_at")
    op.alter_column("dependencies", "github_url_resolve_failed_reason", new_column_name="repository_url_resolve_failed_reason")
    op.add_column('dependencies', sa.Column('status', sa.String(), nullable=False, server_default=sa.text("'pending'") ))
    op.drop_index(op.f('ix_dependencies_github_url_resolve_failed'), table_name='dependencies')
    op.drop_column('dependencies', 'github_url_resolved')
    op.drop_column('dependencies', 'github_url_resolve_failed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column("dependencies", "repository_url_checked_at", new_column_name="github_url_checked_at")
    op.alter_column("dependencies", "repository_url_resolve_failed_reason", new_column_name="github_url_resolve_failed_reason")
    op.add_column('dependencies', sa.Column('github_url_resolve_failed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('dependencies', sa.Column('github_url_resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_dependencies_github_url_resolve_failed'), 'dependencies', ['github_url_resolve_failed'], unique=False)
    op.drop_column('dependencies', 'status')
    # ### end Alembic commands ###
