"""Add repository clone url column

Revision ID: c5864af6233f
Revises: 8bae674e01e4
Create Date: 2025-06-07 12:48:00.188911+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5864af6233f"
down_revision: Union[str, None] = "8bae674e01e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("repositories", sa.Column("clone_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "clone_url")
    # ### end Alembic commands ###
