"""Add additional info columns to repositories table

Revision ID: d03f1b6980cd
Revises: 83222855fffd
Create Date: 2025-06-02 15:59:13.404792+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d03f1b6980cd"
down_revision: Union[str, None] = "83222855fffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("repositories", sa.Column("url", sa.String(), nullable=True))
    op.add_column("repositories", sa.Column("open_issues", sa.Integer(), nullable=True))
    op.add_column("repositories", sa.Column("score", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "score")
    op.drop_column("repositories", "open_issues")
    op.drop_column("repositories", "url")
    # ### end Alembic commands ###
