name: background-worker

on:
  pull_request:
    branches: ["**"]


jobs:
  lint-and-test:
    name: Lint and Test (background-worker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('background-worker/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.2

      - name: Run Linter
        run: |
          cd background-worker/
          golangci-lint run ./...

      - name: Run Tests
        run: |
          cd background-worker/
          go test -v ./...
