name: Deploy API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy to?"
        required: true
        default: "production"
        type: choice
        options:
          - production
    # branches:
    #   - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Deploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
