name: Deploy API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy to?"
        required: true
        default: "production"
        type: choice
        options:
          - production
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # steps:
    #   - name: Trigger Render Deployment
    #     run: |
    #       curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
    #       -H "Authorizzation: Bearer ${{ secrets.RENDER_API_KEY}}" \
    #       -H "Accept: application/json" \
    #       -H "Content-Type: application/json" \
    #       -d '{}'
    #
