name: Deploy Db

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy to?"
        required: true
        default: "production"
        type: choice
        options:
          - Production

jobs:
  migrate:
    name: Migrate Database
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    # env:
    #   SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    #   SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
        
      - name: Run migrations
        # run: supabase db push --project-ref $SUPABASE_PROJECT_REF
        run: supabase db push --db-url ${{ secrets.SUPABASE_MIGRATION_URL }}
