
name: Lint and Test API

on:
  pull_request:
    branches: ["**"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    services:
      test-postgres:
        image: postgres:17
        ports:
          - 5434:5432
        env:
          POSTGRES_USER: test-user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: |
          cd api/
          poetry install

      - name: Run Ruff Linter
        run: |
          cd api/
          poetry run ruff check .

      - name: Run Tests # Tests handle migrations
        run: |
          cd api/
          poetry run pytest
