name: web

on:
  pull_request:
    branches: ["**"]

jobs:
  lint-and-test:
    name: Lint and Test (web)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: |
          cd web/
          pnpm install

      - name: Run ESLint
        run: |
          cd web/
          pnpm lint
