
name: Lint and Test API

on:
  pull_request:
    branches: ["**"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies with Poetry
        run: |
          cd api/
          poetry install

      - name: Run Ruff Linter
        run: |
          cd api/
          poetry run ruff check .

      - name: Run Tests
        run: |
          cd api/
          poetry run pytest
